### PR TITLE
test: add test case for #269

### PR DESCRIPTION
**Pull request by timdeschryver**
@the-ult I've added a workaround in the test cases.

Do you see a possible solution so we don't require this workaround?

### CODE REVIEW

**Comment by the-ult** [comment]
No, I did not see any other solution. But this seems pretty legit. Adding it to the `componentProperties`

Maybe add it as an example test to the example-app itself, instead of an issue test? (harder to find )

**Comment by timdeschryver** [comment]
I think this example already covers that https://github.com/testing-library/angular-testing-library/blob/main/apps/example-app/src/app/examples/08-directive.spec.ts#L28, thoughts?

Also, passing in the props in the template should work. The problem that you experiences is specific because you had html entities in the string... For example, if you just use a simple string with the uppercase pipe, the string gets transormed.

**Comment by the-ult** [comment]
>  For example, if you just use a simple string with the uppercase pipe, the string gets transormed

Yes indeed, that works without any problems. 
Which is why I thought this could be a bug 😇 

I think it is _not_ obvious in [the directive example](https://github.com/testing-library/angular-testing-library/blob/main/apps/example-app/src/app/examples/08-directive.spec.ts#L28), that in case of HTML entities in a string. You'll _need_ to use the `componentProperties`

**Comment by timdeschryver** [comment]
@the-ult thanks for the feedback, I've moved it to the examples folder.

**Pull request merged**
