### PR TITLE
feat: upgrade Angular 14

### LINKED ISSUE #296: Angular 14 support
### Description

Currently standalone components, directives and pipes cannot be tested because they are automatically added to the `declarations` portion when configuring TestBed internally. Angular throws an error when trying to declare a standalone component. 

### Proposed solution

Add the component/directive/pipe-under-test to the imports section of `TestBed.configureTestingModule` if the component is standalone.

### Alternatives considered

There isn't really a way to work around this.

### PR DESCRIPTION
**Pull request by jadengis**
- update @angular/core
- update @angular/cli
- updated @angular/material
- fix standalone components

Closes #296

### CODE REVIEW

**Review by timdeschryver — COMMENTED** [review]
Great, thanks for this PR!
I think a second test that uses standalone components that have a child component will be helpful as well.
Thoughts?

**Comment by jadengis** [comment]
@timdeschryver I've added a test with a child component.

**Review by timdeschryver — APPROVED** [review]
💙

**Comment by timdeschryver** [comment]
@all-contributors please add @jadengis for code, tests

**Pull request merged**
