### PR TITLE
Fix: component setter is overwritten when component properties are set

### PR DESCRIPTION
**Pull request by GlebIrovich**
This PR is meant to fix an issue mentioned [here](https://github.com/testing-library/angular-testing-library/issues/191#issuecomment-806070806).

The problem was that `defineProperty` would overwrite original setter.

Solution is to first retrieve that original setter and make sure it's invoked.

### CODE REVIEW

**Review by timdeschryver — APPROVED** [review]
This is great, thanks!

**Comment by GlebIrovich** [comment]
@timdeschryver when do you think we can have a patch?

**Comment by timdeschryver** [comment]
In a few seconds, it's being released as we speak 😉

**Comment by timdeschryver** [comment]
@all-contributors please add @GlebIrovich  for code, tests

**Pull request merged**
