### PR TITLE
fix: correct peer dependencies

### LINKED ISSUE #270: ... has incorrect peer dependency "@angular/forms@13.0.2"
Hi, there seems to be some odd (correct me if I'm wrong) peer dependencies:

<pre>
warning " > @testing-library/angular@11.0.0" has incorrect peer dependency "@angular/forms@13.0.2".
warning " > @testing-library/angular@11.0.0" has unmet peer dependency "@testing-library/user-event@^13.5.0".
</pre>

### PR DESCRIPTION
**Pull request by timdeschryver**
Closes #270

### CODE REVIEW

**Comment by the-ult** [comment]
Hey @timdeschryver 

How did this resolve the dependencies issue?

I refactored the `angular.json` to `workspace.json` and using the per project configuration with `project.json`

https://blog.nrwl.io/per-project-configuration-storybook-support-for-angular-12-auto-refresh-for-dependency-graph-and-bcd2d1e06658

Atm angular-testing-library has both a `angular.json` and a `workspace.json`

**Comment by timdeschryver** [comment]
@the-ult I re-added the angular.json file as a quick fix. It's probably better to add them as a dev dependency, but I wasn't aware that that would be the proper fix. Another problem is that the build task in the angular file also includes some post-build scripts, which should also be added to the nx file.

**Comment by the-ult** [comment]
I 'll try to make a new PR next week.

Not sure if adding them to the `devDependencies` is the fix. But from the quick test, it seems to work and generate a proper `package.json`.

And thinking: `dependencies` should only include the dependencies you'll need for production it seems logical, not needing them for the `testing-library`

We could ask somebody from the nx team if the above is actually needed. Might be a bug in NX. They should probably skip imports/dependencies, which are only used in tests.

**Comment by timdeschryver** [comment]
@the-ult fyi, it seems like we already got the post-build steps covered - so the only problem are the dependencies.

https://github.com/testing-library/angular-testing-library/blob/main/projects/testing-library/project.json#L38

**Comment by the-ult** [comment]
Indeed. 
I'll try and create a PR tomorrow 👍

**Comment by timdeschryver** [comment]
No rush though @the-ult

**Pull request merged**
