### PR TITLE
feat: auto-cleanup

### LINKED ISSUE #67: getByLabelText returns an old reference in 9.0.0-beta.1
Hi @timdeschryver, after a long time (~1 week) searching what was breaking my tests. I have discovered that the upgrade to beta release was the culprit.

It seems that getByLabelText is using an old reference of fixture the or nativeElement. I have created a repro where you can see the bug (it has cost a lot of hours to reproduce it :sweat_smile:)

[Repository with the test](https://github.com/tonivj5/angular-testing-library/tree/bug/getByLabelText), use the branch `bug/getByLabelText` and run the command `yarn test bug-` to launch it (it should broke :boom:).
```ts
import { Component } from '@angular/core';
import { render } from '../src/public_api';

@Component({
  template: `
    <div>
      <!-- if remove for="name" no error happens -->
      <label for="name">
        <input type="checkbox" id="name" data-testid="checkbox" />
        TEST
      </label>
    </div>
  `,
})
export class BugGetByLabelTextComponent {}

it('first step to reproduce the bug: skip this test to avoid the error or remove the for attribute of label', async () => {
  expect(await render(BugGetByLabelTextComponent)).toBeDefined();
});

it('second step: bug happens :`(', async () => {
  const { getByLabelText, getByTestId } = await render(BugGetByLabelTextComponent);

  const checkboxByTestId = getByTestId('checkbox');
  const checkboxByLabelTest = getByLabelText('TEST');

  expect(checkboxByTestId).toBe(checkboxByLabelTest);
});

```

If you run this test in `master`, it success. If you run this test in beta it breaks, because `checkboxByTestId` and `checkboxByLabelTest` aren't equal, they are two different objects (input html objects). But, if you skip the first test (`it.skip`) the test is successfully. And, other way to pass the test is removing the `for="name"` attribute (I think it happens because, the input is get using `label.control` if `for` is present and linked). This error is a big problem because if, for example, I use `click(checkboxByLabelTest)`, it doesn't run change detection, test fail and it's difficult to determine what is happening.

I think it's related with the update of `@testing-library/dom`, I have tried to downgrade it to master's version, but it continues failing. Maybe, this bug should be reported at `@testing-library/dom` instead of here, but I am not sure, sorry if it so.

Thanks for your work in this library, I'm so exciting using it in my project! :+1:

### PR DESCRIPTION
**Pull request by timdeschryver**
Closes #67

### CODE REVIEW

**Comment by tonivj5** [comment]
You're a magician. I was just trying to see what is happening. And the only thing that I have discovered is that if I disable `removeAngularAttributes` the error goes away... Very good catch see that the body is mantaining all templates :+1:

**Comment by tonivj5** [comment]
Thinking about the fix, this error happens in every angular+jest setup, isn't it? :confused:

**Comment by tonivj5** [comment]
I have found where happens the "bug"
image

It seems to be on the Angular side. It query for old roots to remove them, but, how the id is being remove, Angular isn't be able to find them :crying_cat_face:

So, it answer my last question! :clap:

**Comment by timdeschryver** [comment]
Hmm interesting, thanks @tonivj5 !
Do you think we should still do this cleanup? I'm thinking of reverting the change to remove the root.

I'm definitely going to change the default in this version 😅

**Comment by timdeschryver** [comment]
(if you want you can create a PR)

**Comment by tonivj5** [comment]
Yes, if we use `removeAngularAttributes` the cleanup must be, because it prevents Angular from remove old roots. However, I think we should leave to Angular the task of remove its roots. I'm going to open a new PR proposing other cleanup (I think simpler) :+1:

> I'm definitely going to change the default in this version :sweat_smile:
It could follow being enable by default, I guess it's enable by default to help in debug log (cleaner, I supose), isn't it?

**Comment by tonivj5** [comment]
Here is the PR https://github.com/testing-library/angular-testing-library/pull/69 :+1:

**Pull request merged**
